Repository arturbac/fixed_math, pull requests merged in 2025-05, with the labels that each got.

#10 to_string() and from_string()
  examples/iostream_example.cpp
  examples/string_conversion_example.cpp
  fixed_lib/include/fixedmath/detail/common.h
  fixed_lib/include/fixedmath/fixed_string.h
  fixed_lib/include/fixedmath/iostream.h
  fixed_lib/include/fixedmath/std_formatter.h
  unit_tests/CMakeLists.txt
  unit_tests/fixed_string_unittest.cc
Labels: enhancement

#12 add clang::trivial_abi attribute
  CMakePresets.json
  fixed_lib/include/fixedmath/types.h
Labels: enhancement

#14 modulo operator and functions
  fixed_lib/include/fixedmath/fixed_math.hpp
  fixed_lib/include/fixedmath/math.h
  fixed_lib/include/fixedmath/types.h
  unit_tests/CMakeLists.txt
  unit_tests/modulo_ut.cc
Labels: enhancement

#15 tests for string convertion
  fixed_lib/include/fixedmath/fixed_string.h
  unit_tests/CMakeLists.txt
  unit_tests/fixed_string_unittest.cc
  unit_tests/string_convertion_ut.cc
Labels: bug

#17 reenable consteval on from_string test
  fixed_lib/include/fixedmath/fixed_string.h
  unit_tests/string_convertion_ut.cc
Labels: enhancement

#16 Fmod perf.cc update
  perf_test_suite/perf.cc
Labels: enhancement

#20 update doc, add exampels to build
  docs/index.md
  examples/CMakeLists.txt
  examples/iostream.cc
  examples/string_conversion.cc
Labels: documentation, enhancement
